version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
        environment:
          - "discovery.type=single-node"
          - "cluster.name=datashare"
          - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        name: elasticsearch
      - image: redis:4.0.1-alpine
        name: redis

    working_directory: ~/app

    environment:
      MAVEN_OPTS: "-Xms256m -Xmx256m"

    dependencies:
      override:

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn validate

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn test

      - run: mvn -Dmaven.test.skip=true package

  build_front:
    docker:
      - image: circleci/node:8.9.4
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
        environment:
          - "discovery.type=single-node"
          - "cluster.name=datashare"
          - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        name: elasticsearch
    working_directory: ~/app
    steps:
      - add_ssh_keys:
        fingerprints:
          - "40:0b:cf:14:68:05:6d:a8:fd:76:4d:b7:75:ea:1c:b4"
      - run:
        name: checkout
        command: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:ICIJ/datashare-client.git
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest yarn@latest'

workflows:
  version: 2
  tagged_build:
    jobs:
      - build
      - build_front

#workflows:
#  version: 2
#    un-tagged-build:
#      jobs:
#        - build:
#          filters:
#            tags:
#              ignore: /^[0-9.]*/
#    tagged_build:
#      jobs:
#        - build:
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#             only: /^[0-9.]*/
#       - build_front:
#         requires:
#           - build