version: '2'
services:
  redis:
    image: redis:4.0.1-alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    environment:
      - "discovery.type=single-node"
      #- "ES_JAVA_OPTS=-Des.enforce.bootstrap.checks=false"
    ports:
      - "9200:9200"
      - "9300:9300"
